apiVersion: v1
kind: Secret
metadata:
  name: saqbol-secret
  namespace: saqbol
type: Opaque
stringData:
  POSTGRES_PASSWORD: "saqbol"
  DATABASE_URL: "postgres://saqbol:saqbol@postgres:5432/saqbol?sslmode=disable"
  JWT_ACCESS_SECRET: "change_me_access_secret_in_production"
  JWT_REFRESH_SECRET: "change_me_refresh_secret_in_production"
