// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: ml/v1/ml.proto

package mlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Locale        string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_ml_v1_ml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_v1_ml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_ml_v1_ml_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ClassifyRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ClassifyRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type ClassifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`
	Probability   float64                `protobuf:"fixed64,2,opt,name=probability,proto3" json:"probability,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Triggers      []string               `protobuf:"bytes,4,rep,name=triggers,proto3" json:"triggers,omitempty"`
	Advice        string                 `protobuf:"bytes,5,opt,name=advice,proto3" json:"advice,omitempty"`
	LatencyMs     int32                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,7,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_ml_v1_ml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_v1_ml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_ml_v1_ml_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *ClassifyResponse) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *ClassifyResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ClassifyResponse) GetTriggers() []string {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *ClassifyResponse) GetAdvice() string {
	if x != nil {
		return x.Advice
	}
	return ""
}

func (x *ClassifyResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ClassifyResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

var File_ml_v1_ml_proto protoreflect.FileDescriptor

const file_ml_v1_ml_proto_rawDesc = "" +
	"\n" +
	"\x0eml/v1/ml.proto\x12\fsaqbol.ml.v1\"W\n" +
	"\x0fClassifyRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\"\xe2\x01\n" +
	"\x10ClassifyResponse\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12 \n" +
	"\vprobability\x18\x02 \x01(\x01R\vprobability\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1a\n" +
	"\btriggers\x18\x04 \x03(\tR\btriggers\x12\x16\n" +
	"\x06advice\x18\x05 \x01(\tR\x06advice\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x05R\tlatencyMs\x12#\n" +
	"\rmodel_version\x18\a \x01(\tR\fmodelVersion2\xb0\x01\n" +
	"\x0eScamClassifier\x12I\n" +
	"\bClassify\x12\x1d.saqbol.ml.v1.ClassifyRequest\x1a\x1e.saqbol.ml.v1.ClassifyResponse\x12S\n" +
	"\x0eClassifyStream\x12\x1d.saqbol.ml.v1.ClassifyRequest\x1a\x1e.saqbol.ml.v1.ClassifyResponse(\x010\x01B,Z*github.com/saqbol/backend/proto/ml/v1;mlv1b\x06proto3"

var (
	file_ml_v1_ml_proto_rawDescOnce sync.Once
	file_ml_v1_ml_proto_rawDescData []byte
)

func file_ml_v1_ml_proto_rawDescGZIP() []byte {
	file_ml_v1_ml_proto_rawDescOnce.Do(func() {
		file_ml_v1_ml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_v1_ml_proto_rawDesc), len(file_ml_v1_ml_proto_rawDesc)))
	})
	return file_ml_v1_ml_proto_rawDescData
}

var file_ml_v1_ml_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ml_v1_ml_proto_goTypes = []any{
	(*ClassifyRequest)(nil),  // 0: saqbol.ml.v1.ClassifyRequest
	(*ClassifyResponse)(nil), // 1: saqbol.ml.v1.ClassifyResponse
}
var file_ml_v1_ml_proto_depIdxs = []int32{
	0, // 0: saqbol.ml.v1.ScamClassifier.Classify:input_type -> saqbol.ml.v1.ClassifyRequest
	0, // 1: saqbol.ml.v1.ScamClassifier.ClassifyStream:input_type -> saqbol.ml.v1.ClassifyRequest
	1, // 2: saqbol.ml.v1.ScamClassifier.Classify:output_type -> saqbol.ml.v1.ClassifyResponse
	1, // 3: saqbol.ml.v1.ScamClassifier.ClassifyStream:output_type -> saqbol.ml.v1.ClassifyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ml_v1_ml_proto_init() }
func file_ml_v1_ml_proto_init() {
	if File_ml_v1_ml_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_v1_ml_proto_rawDesc), len(file_ml_v1_ml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_v1_ml_proto_goTypes,
		DependencyIndexes: file_ml_v1_ml_proto_depIdxs,
		MessageInfos:      file_ml_v1_ml_proto_msgTypes,
	}.Build()
	File_ml_v1_ml_proto = out.File
	file_ml_v1_ml_proto_goTypes = nil
	file_ml_v1_ml_proto_depIdxs = nil
}
