// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.0
// source: ml/v1/ml.proto

package mlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScamClassifier_Classify_FullMethodName       = "/saqbol.ml.v1.ScamClassifier/Classify"
	ScamClassifier_ClassifyStream_FullMethodName = "/saqbol.ml.v1.ScamClassifier/ClassifyStream"
)

// ScamClassifierClient is the client API for ScamClassifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScamClassifierClient interface {
	Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
	ClassifyStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClassifyRequest, ClassifyResponse], error)
}

type scamClassifierClient struct {
	cc grpc.ClientConnInterface
}

func NewScamClassifierClient(cc grpc.ClientConnInterface) ScamClassifierClient {
	return &scamClassifierClient{cc}
}

func (c *scamClassifierClient) Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, ScamClassifier_Classify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scamClassifierClient) ClassifyStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClassifyRequest, ClassifyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ScamClassifier_ServiceDesc.Streams[0], ScamClassifier_ClassifyStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClassifyRequest, ClassifyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScamClassifier_ClassifyStreamClient = grpc.BidiStreamingClient[ClassifyRequest, ClassifyResponse]

// ScamClassifierServer is the server API for ScamClassifier service.
// All implementations must embed UnimplementedScamClassifierServer
// for forward compatibility.
type ScamClassifierServer interface {
	Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	ClassifyStream(grpc.BidiStreamingServer[ClassifyRequest, ClassifyResponse]) error
	mustEmbedUnimplementedScamClassifierServer()
}

// UnimplementedScamClassifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScamClassifierServer struct{}

func (UnimplementedScamClassifierServer) Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedScamClassifierServer) ClassifyStream(grpc.BidiStreamingServer[ClassifyRequest, ClassifyResponse]) error {
	return status.Error(codes.Unimplemented, "method ClassifyStream not implemented")
}
func (UnimplementedScamClassifierServer) mustEmbedUnimplementedScamClassifierServer() {}
func (UnimplementedScamClassifierServer) testEmbeddedByValue()                        {}

// UnsafeScamClassifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScamClassifierServer will
// result in compilation errors.
type UnsafeScamClassifierServer interface {
	mustEmbedUnimplementedScamClassifierServer()
}

func RegisterScamClassifierServer(s grpc.ServiceRegistrar, srv ScamClassifierServer) {
	// If the following call panics, it indicates UnimplementedScamClassifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScamClassifier_ServiceDesc, srv)
}

func _ScamClassifier_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScamClassifierServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScamClassifier_Classify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScamClassifierServer).Classify(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScamClassifier_ClassifyStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ScamClassifierServer).ClassifyStream(&grpc.GenericServerStream[ClassifyRequest, ClassifyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScamClassifier_ClassifyStreamServer = grpc.BidiStreamingServer[ClassifyRequest, ClassifyResponse]

// ScamClassifier_ServiceDesc is the grpc.ServiceDesc for ScamClassifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScamClassifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saqbol.ml.v1.ScamClassifier",
	HandlerType: (*ScamClassifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _ScamClassifier_Classify_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClassifyStream",
			Handler:       _ScamClassifier_ClassifyStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ml/v1/ml.proto",
}
